### PR TITLE
Update flask dependency to 2.3.3

### PR DESCRIPTION
**Pull request by thepetk**
## What does this PR do?:

This PR updates the version of `flask` to `2.3.3` in order to avoid the error:

```bash
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
(/home/tpetkos/github/thepetk/devfile-samples/devfile-sample-python-basic/venv/
lib/python3.10/site-packages/werkzeug/urls.py)
```

As mentioned in the [changelog](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-3) the `2.3.3` version uses `Werkzeug >= 2.3.7`.

## Notes for the Reviewer

In order to reproduce the error try to install dependencies and run flask inside main branch (I managed to do that with python version `3.10.x`:

```
python3 -m venv venv/
source venv/bin/activate
pip3 install -r requirements.txt
flask run
```
You can verify that the bug has been fixed by checking out to this branch, try again to run flask.

## Acceptance Criteria

- [x] Tested with Odo, RHTAP

### CODE REVIEW

**Review by kim-tsao — COMMENTED** [review]
The existing python 2.1.0 and 3.0.0. stacks depend on this repo but we can't really bump up the devfile versions because this dependency is not versioned itself.   Has there been sufficient testing done on our clients (ODC, Odo, etc) to ensure this will not cause breakage? I don't know if our existing integration-tests have sufficient coverage either (it looks like it's dependent on the original odo repo https://github.com/devfile/integration-tests/blob/main/tests/examples/source/devfiles/python/devfile-registry.yaml#L48) but maybe it's worth a look

**Comment by thepetk** [comment]
> Has there been sufficient testing done on our clients (ODC, Odo, etc) to ensure this will not cause breakage?

I've tested with odo and RHTAP (HAS) for both versions and seems to be ok. Note that at the moment there is a breakage as both `2.1.0` and `3.0.0` cannot execute `run-app` command because of the incompatibility of `flask 2.1.0` and `python 3.9.x`. The reason behind this issue, most probably, is because flask in version `2.1.0` uses the latest `werkzeug` version which is not compatible anymore.

Regarding ODC I wasn't able to find a way to test this repo. I cannot find a proper way to `import from Git` as mentioned [here](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md#console)

> I don't know if our existing integration-tests have sufficient coverage either (it looks like it's dependent on the original odo repo https://github.com/devfile/integration-tests/blob/main/tests/examples/source/devfiles/python/devfile-registry.yaml#L48) 

I see this devfile is using `python: 3.7.x` as image (https://github.com/devfile/integration-tests/blob/main/tests/examples/source/devfiles/python/devfile-registry.yaml#L30). The latest flask version supported from 3.7.x is the `flask 2.2.5`. On the other hand `python 3.7.x` is quite old, so I think it would be nice to upgrade to a newer version.

**Comment by kim-tsao** [comment]
> > Has there been sufficient testing done on our clients (ODC, Odo, etc) to ensure this will not cause breakage?
> 
> I've tested with odo and RHTAP (HAS) for both versions and seems to be ok. Note that at the moment there is a breakage as both `2.1.0` and `3.0.0` cannot execute `run-app` command because of the incompatibility of `flask 2.1.0` and `python 3.9.x`. The reason behind this issue, most probably, is because flask in version `2.1.0` uses the latest `werkzeug` version which is not compatible anymore.
> 
> Regarding ODC I wasn't able to find a way to test this repo. I cannot find a proper way to `import from Git` as mentioned [here](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md#console)
> 
> > I don't know if our existing integration-tests have sufficient coverage either (it looks like it's dependent on the original odo repo https://github.com/devfile/integration-tests/blob/main/tests/examples/source/devfiles/python/devfile-registry.yaml#L48)
> 
> I see this devfile is using `python: 3.7.x` as image (https://github.com/devfile/integration-tests/blob/main/tests/examples/source/devfiles/python/devfile-registry.yaml#L30). The latest flask version supported from 3.7.x is the `flask 2.2.5`. On the other hand `python 3.7.x` is quite old, so I think it would be nice to upgrade to a newer version.

Yes the integration tests are old and unmaintained.  I thought there might be something of value there for us to reuse.  Since this change does not affect our samples, which ODC is sensitive to, I'll approve based on the testing that you've done.

**Review by kim-tsao — APPROVED** [review]

**Comment by thepetk** [comment]
> Yes the integration tests are old and unmaintained. I thought there might be something of value there for us to reuse. Since this change does not affect our samples, which ODC is sensitive to, I'll approve based on the testing that you've done.

@kim-tsao after your approval I've re-ran successfully tests for:
* RHTAP (HAS)
* Odo
* ODC (v 4.13)
* Che (by creating a workspace as mentioned [here](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md#che))

FYI I don't have the permissions to merge :)

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
